AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sean-bot

  Sample SAM Template for sean-bot

  '
Globals:
  Function:
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    Environment:
      Variables:
        REGION:
          Ref: region
        DB_HOST:
          Ref: dbHost
        DB_NAME:
          Ref: dbName
        DB_USER:
          Ref: dbUser
        DB_PASSWORD:
          Ref: dbPassword
        HISTORY_QUEUE_URL:
          Ref: HistoryQueue
        SLACK_WORKSPACE:
          Ref: slackWorkspace
        SLACK_TOKEN:
          Ref: slackToken
        SLACK_BOT_USER_ID:
          Ref: slackBotUserID
    Timeout: 30
Parameters:
  region:
    Type: String
  dbHost:
    Type: String
  dbName:
    Type: String
  dbUser:
    Type: String
  dbPassword:
    Type: String
  slackToken:
    Type: String
  slackWorkspace:
    Type: String
  slackBotUserID:
    Type: String
Resources:
  ProcessMessage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-yqsowj27uami/eda4c652aa34b19732cbb3adb53c5094
      Policies:
      - ComprehendBasicAccessPolicy: {}
      - SQSSendMessagePolicy:
          QueueName:
            Fn::GetAtt:
            - HistoryQueue
            - QueueName
      Events:
        ProcessMessage:
          Type: Api
          Properties:
            Path: /process
            Method: post
  ProcessHistory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-yqsowj27uami/e39b81cc98f0c90df22746a91b94cf98
      Policies:
      - ComprehendBasicAccessPolicy: {}
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - HistoryQueue
              - Arn
            BatchSize: 10
  HistoryQueue:
    Type: AWS::SQS::Queue
Outputs:
  ProcessMessageApi:
    Description: API Gateway endpoint URL for Prod stage for Process Message function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process/
  ProcessMessage:
    Description: Process Message Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ProcessMessage
      - Arn
  ProcessMessageIamRole:
    Description: Implicit IAM Role created for Process Message function
    Value:
      Fn::GetAtt:
      - ProcessMessageRole
      - Arn
