version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sean-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yqsowj27uami"
s3_prefix = "sean-bot"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

